### ISSUE TITLE
camera exposure is low

### ISSUE THREAD

**Issue by patmarion** [openhumanoids/openni2-camera-lcm#6]
Has anyone noticed this?  When I use this driver on my asus xiton the RGB image is dark relative to the image i get when i use the ROS openni2 driver.  Maybe there is an auto-exposure setting that is missing from this driver.

**Comment by wxmerkt** [comment]
Yes, noticed this as well. The issue is that the variables controlling it are unitialised and thus false:

1. https://github.com/openhumanoids/openni2-camera-lcm/blob/master/include/openni2_camera/openni2_driver.h#L182-L183
2. https://github.com/openhumanoids/openni2-camera-lcm/blob/master/src/openni2_driver.cpp#L238-L239

Setting them to true in the (2) should fix it

**Comment by patmarion** [comment]
awesome, thanks!  I'll try this next time i use the driver.  Do you see any reason not to always set them to true?  It looks like those lines were commented out intentionally.

**Comment by wxmerkt** [comment]
Yes, I do believe that to be an unintentional omission when making it work without dynamic reconfigure from ROS (but I may be mistaken)  - we may just default them to true for now and make them a command line parameter
